# Generated by Django 2.1 on 2018-08-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertFinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concertvenue',
            old_name='venue',
            new_name='venue_name',
        ),
        migrations.AlterField(
            model_name='concertinfo',
            name='ticket_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
