# Generated by Django 2.1 on 2018-10-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertFinder', '0005_auto_20180927_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertinfo',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='concertinfo',
            name='image',
            field=models.CharField(default='static/ucr.jpg', max_length=255),
        ),
    ]
