# Generated by Django 2.1 on 2018-10-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertFinder', '0006_auto_20181005_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concertinfo',
            old_name='note',
            new_name='note_approved',
        ),
        migrations.AddField(
            model_name='concertinfo',
            name='note_attending',
            field=models.CharField(default='', max_length=255),
        ),
    ]
