# Generated by Django 2.1 on 2018-10-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concertFinder', '0007_auto_20181009_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_attending', models.CharField(default='', max_length=255)),
                ('note_featured', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='concertinfo',
            name='note_approved',
        ),
        migrations.RemoveField(
            model_name='concertinfo',
            name='note_attending',
        ),
        migrations.AddField(
            model_name='concertinfo',
            name='note_attend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending', to='concertFinder.ConcertNote'),
        ),
        migrations.AddField(
            model_name='concertinfo',
            name='note_feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='concertFinder.ConcertNote'),
        ),
    ]
