# Generated by Django 2.1 on 2018-10-10 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concertFinder', '0008_auto_20181009_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertinfo',
            name='note_attend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending', to='concertFinder.ConcertNote'),
        ),
        migrations.AlterField(
            model_name='concertinfo',
            name='note_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='concertFinder.ConcertNote'),
        ),
    ]
